/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author PC
 */
public class PnBanHang extends javax.swing.JPanel {
    //tạo các biến instance cho PnBanHangForm và PnHoaDonForm 
    //và cung cấp một phương thức để chuyển tab
    private PnBanHangForm pnBanHang; // Khai báo biến instance
    private PnHoaDonForm pnHoaDon;
    
    public PnBanHang() {
        initComponents();
        
        this.pnBanHang = new PnBanHangForm(this);
        this.pnHoaDon = new PnHoaDonForm();
        
        // Xóa tab mặc định (nếu NetBeans tạo sẵn)
        tabQLBanHang.removeAll();

        // Thêm tab mới với form riêng
        tabQLBanHang.addTab("Bán hàng", pnBanHang);
        tabQLBanHang.addTab("Hóa đơn", pnHoaDon);
    }
    
    public void switchToHoaDonTabAndShowDetail(int maHD) {
        // 1. Chuyển sang tab Hóa đơn (tab index 1)
        tabQLBanHang.setSelectedIndex(1);
        
        // 2. Gọi hàm tải chi tiết hóa đơn trong PnHoaDonForm
        // Bạn cần đảm bảo PnHoaDonForm có phương thức này
        pnHoaDon.hienThiHoaDonMoi(maHD); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabQLBanHang = new javax.swing.JTabbedPane();
        tabBanHang = new javax.swing.JTabbedPane();
        tabHoaDon = new javax.swing.JTabbedPane();

        tabQLBanHang.addTab("Bán hàng", tabBanHang);
        tabQLBanHang.addTab("Hóa đơn", tabHoaDon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabQLBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabQLBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabBanHang;
    private javax.swing.JTabbedPane tabHoaDon;
    private javax.swing.JTabbedPane tabQLBanHang;
    // End of variables declaration//GEN-END:variables
}
